# Generated by Django 4.2.3 on 2023-08-02 13:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('25e0c59b-3e1b-453b-bcd2-c30dcbaac89a'), editable=False, unique=True),
        ),
    ]
