# Generated by Django 4.2.3 on 2023-08-02 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8f1220ae-f525-4679-89c3-ce8a22e0b606'), editable=False, unique=True),
        ),
    ]
