# Generated by Django 4.2.3 on 2023-08-03 00:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('320245fd-9860-466c-8a54-9c932c3b1170'), editable=False),
        ),
    ]
